baseURL = 'https://ciruelasandia.github.io/'
locale = 'zh-cn'
title = 'Les Petits Riens'
copyright = '© 2026 Les Petits Riens'
theme = "PaperMod"
defaultContentLanguage = "zh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowToc = true
  TocOpen = true
  homeInfoParams = { Title = "欢迎来到我的角落", Content = "生活琐事，偶有所思。" }

[services]
  [services.googleAnalytics]
    ID = "G-VJVB0NE0N2"